services:
  nginx-server:
    image: nginx:1
    ports:
      - 80:80
    networks:
      - mynet1
  web-server:
    image: matagi1209/docker-temp:1
    ports:
      - 8080:8080
    networks:
      - mynet1
  db-container:
    image: postgres:13.20-alpine3.20
    ports:
      - 5432:5432
    networks:
      - mynet1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwer1234
    volumes:
      - type: volume
        source: test
        target: /var/lib/postgresql/data
  
volumes:
  test: {}

networks:
  mynet1:
    driver: bridge